### ISSUE TITLE
Sidebar component padding and spacing

### ISSUE THREAD

**Issue by xraystyle1980** [decentdao/fractal-interface#1667]
Design update needed for sidebar component. See screenshot. Padding was added between the button and menu. 
[In Figma](https://www.figma.com/file/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?type=design&node-id=2521%3A4083&mode=dev&t=9Q4JWciIQe6L5wqD-1)
![image](https://github.com/decentdao/fractal-interface/assets/18615633/5c5cd58d-0b84-4a84-9e9d-08b9910d7f63)

Also notice that there should be no "gap" in the menu above language, just the stroke.

**Comment by xraystyle1980** [comment]
> @xraystyle1980 @tomstuart123 This should be in the latest root reskin PR - can you verify pls and if everything correct - close the issue

Thanks @mudrila 
2 things I see: 
The buttons active state adds a border (which is correct) but in adding the border, an additional 1px is added to the overall size causing the button to "jump". Suggest adding the border to the default and hover and matching the background color.

@nicolaus-sherrill anything else?

**Comment by nicolaus-sherrill** [comment]
The new hover & active behaviors are onnnnnn point
However, the padding on these items is producing rectangular shapes instead of squares, and the icons are slightly off-center to the right.

<img width="70" alt="Screenshot 2024-05-09 at 1 11 31 PM" src="https://github.com/decentdao/fractal-interface/assets/62394931/5ed0fadc-8695-4670-b3e3-4c906475d979">

We ought to see them nice and square'd up and evenly spaced like this, and reduce that corner radius to 4px:

<img width="452" alt="Screenshot 2024-05-09 at 1 12 44 PM" src="https://github.com/decentdao/fractal-interface/assets/62394931/da410f78-dc00-40bd-9fb0-1c5310f4df69">

**Comment by adamgall** [comment]
Completed via https://github.com/decentdao/fractal-interface/pull/1759
