### ISSUE TITLE
Proposal Details row single line

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-interface#1700]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiY2NhZDFmZmUtZDU4ZS00MjM4LWJiY2EtY2MwOTMxNTg1NWNmIiwiZGVwbG95X2lkIjoiNjYzYjhmOWZjZDQ0NDQwMDA4MzIwNjYzIiwiaWQiOiIyNmUxOGY1MS01YThmLTQxYmQtOWFhMC1jYWZlMTlhNjZmNzYifQ==)

Text formatting is pushing to two lines. We should get this down to one line for every item in these details.
<details><summary>Browser metadata</summary>

```
Path:      /proposals/3?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2
Browser:   Firefox 125.0 on Mac OS 10.15
Viewport:  1518 x 912 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1578.app.dev.fractalframework.xyz%2Fproposals%2F3%3Fdao%3Dsep%3A0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=125.0&resolution=1518x912&speed=1&start=true&ref=netlify-source)

</details>

[Open Deploy Preview](https://deploy-preview-1578.app.dev.fractalframework.xyz/proposals/3?dao=sep:0x6DEBaE44A8f592733D1D4854b27108F145A1fdb2) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=663b8f9fcd44440008320663&commentID=663bb3d24b124c0b6ab915b6&resolution=resolved)

_Originally posted by @nicolaus-sherrill in https://github.com/decentdao/fractal-interface/issues/1578#issuecomment-2101048898_

**Comment by Da-Colon** [comment]
@nicolaus-sherrill What Date format would you like to you for dates (I imagine we will use this for anywhere else where a date is displayed)

**Comment by nicolaus-sherrill** [comment]
We should probably switch to `MM/DD/YYYY` to condense the dates as much as possible. Long month names like September are going to create some formatting headaches. 

I'm assuming most of our users are US-based, but @xraystyle1980 are there any globalization standards we should consider here?

**Comment by adamgall** [comment]
I believe most are European. Also, we need the time included. And time
zone. This has all been feedback from Shutter.

**Comment by nicolaus-sherrill** [comment]
Oh word?

In that case, if we use [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) international standard for date and time notation, the formatting is as follows:

Dates — `YYYY-MM-DD`
Time — 24 hour clock, `00:00–23:59`
Timezone — can be represented as ±00 from UTC, with Z used for UTC; `22:00Z` for UTC, `22:00 -06` for Central Time

Full Notation — `YYYY-MM-DD HH:MM ±ZZ` or `2024-05-09 13:04 -06`

Timezone is the trickiest notation to understand and communicate accurately because of daylight savings. I followed this [Wiki page](https://en.wikipedia.org/wiki/Time_zone#Notation), which pulls from the same ISO 8601 standard. [This guide came from NASA and Cambridge.](https://www.cl.cam.ac.uk/~mgk25/iso-time.html)


I would love a fact check from our European contributors @tomstuart123 @mudrila @DarksightKellar @xanaramoss

**Comment by xraystyle1980** [comment]
We can apply some formatting rules and max-widths to help wrangle in the long formats too
![image](https://github.com/decentdao/fractal-interface/assets/18615633/9e93f048-8f77-439f-b2d5-83989680f6cd)

**Comment by nicolaus-sherrill** [comment]
CC @adamgall @tomstuart123 
Trice and I huddled and I would like to propose this single column solution for this pattern in the app:
![Details](https://github.com/decentdao/fractal-interface/assets/62394931/5bbbabb1-387a-4cd2-a6c3-3dd0a9e465e7)

It's more flexible and reduces the risk of overlapping elements entirely when text strings get long. However, it will add some debt for us as it is a redesign and this pattern shows up with some variation in a few places across the app.

If you're not concerned, I'll open up a separate issue to tackle this (because this is no longer related to the Date/Time formatting conversation above). But please challenge/flag if it's going to slow things down.

**Comment by tomstuart123** [comment]
**Re; new column solution -** yep I'm aligned with you on both parts @nicolaus-sherrill 

        1) That looks really slick.... 2) with all the things we have to do by launch date we can consider this a p2 nice to have

**re; the dates** - as you say @nicolaus-sherrill these are tricky becuase of the confusion between day / month AND the confusion in GMT vs. other timezone (which shutter also raised before). 

@nicolaus-sherrill how big of a deal is the current two line for you? I.e. do we need to have all this decided and implemented by launch considering its a bit nuanced?

If yes, then the change I'd back is switching to [YYYY-MM-DD + 24hour time in LOCAL TIME].... but would prefer if we keep the hover states for UTC. So both are shown to the user as options. I also like the idea of keeping the hover state as the long date ( 28 the may 2020 etc) just in case they have confusion around the month/day ordering

**Comment by nicolaus-sherrill** [comment]
Displaying 24 hour time in local time would further compact that date-time notation. I can get behind that. (I will always favor the more concise solution 😝)

In the scheme of things, the two-line visual wrapping is not a big deal for me; we could have worse visual performance. So no we don't need to have everything decided and implemented by launch. We can P2 this for now.

**Comment by tomstuart123** [comment]
no objections. I still see it as a nice to have but considering we've made a lot of progress, go for it

**Comment by adamgall** [comment]
Closed via https://github.com/decentdao/fractal-interface/pull/1791
